name: todo app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter build web

      # Dockerfileの生成を修正
      - name: Create Docker configurations
        run: |
          # Dockerfile作成
          cat > Dockerfile << 'EOL'
          FROM nginx:alpine
          WORKDIR /usr/share/nginx/html
          COPY build/web .
          COPY nginx.conf /etc/nginx/conf.d/default.conf
          EXPOSE 8080
          EOL
          
          # nginx.conf作成
          cat > nginx.conf << 'EOL'
          server {
              listen 8080;
              server_name localhost;
              root /usr/share/nginx/html;
              index index.html;
              location / {
                  try_files $uri $uri/ /index.html;
              }
              # Flutter用の追加設定
              location /assets/ {
                  expires 1y;
                  add_header Cache-Control "public, no-transform";
              }
          }
          EOL

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: 'flutter-todo-442601'  # プロジェクトIDを追加

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Cloud Runへのデプロイを修正
      - name: 'Deploy to Cloud Run'
        id: 'deploy'  # IDを追加
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'flutter-web-app'
          region: 'asia-northeast1'
          source: '.'
          env_vars: |
            NGINX_PORT=8080
          port: 8080
          allow-unauthenticated: true

      - name: 'Show Output'
        run: 'echo ${{ steps.deploy.outputs.url }}'