name: todo app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter build web

      # 動的にDockerfileとnginx.confを生成
      - name: Create Docker configurations
        run: |
          # Dockerfile作成
          echo "FROM nginx:alpine" > Dockerfile
          echo "COPY build/web /usr/share/nginx/html" >> Dockerfile
          echo "COPY nginx.conf /etc/nginx/conf.d/default.conf" >> Dockerfile
          echo "EXPOSE 8080" >> Dockerfile
          
          # nginx.conf作成
          echo 'server {' > nginx.conf
          echo '    listen 8080;' >> nginx.conf
          echo '    server_name localhost;' >> nginx.conf
          echo '    root /usr/share/nginx/html;' >> nginx.conf
          echo '    index index.html;' >> nginx.conf
          echo '    location / {' >> nginx.conf
          echo '        try_files $uri $uri/ /index.html;' >> nginx.conf
          echo '    }' >> nginx.conf
          echo '}' >> nginx.conf

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Cloud RunへのデプロイをDockerビルド込みで実行
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'flutter-web-app'
          region: 'asia-northeast1'
          source: '.'  # Dockerfileがあるディレクトリを指定
          
      # デプロイ後のURLを出力
      - name: 'Show Output'
        run: 'echo ${{ steps.deploy.outputs.url }}'