name: todo app

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Flutter Build
        run: |
          flutter pub get
          flutter build web --release
          echo "Flutter build completed"

      - name: Create Docker configurations
        run: |
          cat > Dockerfile << EOF
          FROM nginx:alpine
          COPY build/web /usr/share/nginx/html/
          COPY nginx.conf /etc/nginx/conf.d/default.conf
          EXPOSE 8080
          EOF
          
          cat > nginx.conf << EOF
          server {
              listen 8080;
              server_name localhost;
              root /usr/share/nginx/html;
              index index.html;
              location / {
                  try_files \$uri \$uri/ /index.html;
              }
          }
          EOF

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure gcloud CLI
        run: |
          gcloud config set project flutter-todo-442601

      - name: 'Deploy to Cloud Run'
        run: |
          # Submit the build with explicit project ID
          gcloud builds submit --project=flutter-todo-442601 --tag gcr.io/flutter-todo-442601/flutter-web-app

          # Deploy to Cloud Run with explicit project ID
          gcloud run deploy flutter-web-app \
            --project=flutter-todo-442601 \
            --image gcr.io/flutter-todo-442601/flutter-web-app \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080

      - name: Get Service URL
        run: |
          gcloud run services describe flutter-web-app \
            --project=flutter-todo-442601 \
            --region asia-northeast1 \
            --format='get(status.url)'