name: todo app

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter build web

      - name: Create Docker configurations
        run: |
          # Dockerfile作成
          cat > Dockerfile << 'EOL'
          # Build stage
          FROM nginx:alpine
          
          # Update nginx user permissions
          RUN chown -R nginx:nginx /var/cache/nginx && \
              chown -R nginx:nginx /var/log/nginx && \
              chown -R nginx:nginx /etc/nginx/conf.d
          
          # Create nginx user directory
          RUN mkdir -p /usr/share/nginx/html && \
              chown -R nginx:nginx /usr/share/nginx/html
          
          # Copy built files
          COPY --chown=nginx:nginx build/web /usr/share/nginx/html/
          COPY nginx.conf /etc/nginx/conf.d/default.conf
          
          # Switch to non-root user
          USER nginx
          
          EXPOSE 8080
          EOL
          
          # nginx.conf作成
          cat > nginx.conf << 'EOL'
          server {
              listen 8080;
              server_name localhost;
              
              root /usr/share/nginx/html;
              index index.html;
              
              location / {
                  try_files $uri $uri/ /index.html;
              }
              
              location /assets/ {
                  expires 1y;
                  add_header Cache-Control "public, no-transform";
              }
              
              # Add security headers
              add_header X-Frame-Options "SAMEORIGIN";
              add_header X-Content-Type-Options "nosniff";
              add_header X-XSS-Protection "1; mode=block";
          }
          EOL

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: 'flutter-todo-442601'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud builds submit --tag gcr.io/flutter-todo-442601/flutter-web-app
          gcloud run deploy flutter-web-app \
            --image gcr.io/flutter-todo-442601/flutter-web-app \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars NGINX_PORT=8080

      - name: Get Service URL
        run: |-
          echo "Service URL: $(gcloud run services describe flutter-web-app --region asia-northeast1 --format 'value(status.url)')"