name: todo app

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      # Flutterビルドのステップを分割して、各段階を確認
      - name: Flutter Clean
        run: flutter clean

      - name: Get packages
        run: flutter pub get

      - name: Verify directories before build
        run: |
          pwd
          ls -la

      - name: Build Flutter web
        run: |
          flutter build web --release
          echo "Flutter build completed"
          ls -la build/
          ls -la build/web/

      - name: Create Docker configurations
        run: |
          # Dockerfile作成
          cat > Dockerfile << 'EOL'
          FROM nginx:alpine
          COPY build/web /usr/share/nginx/html/
          COPY nginx.conf /etc/nginx/conf.d/default.conf
          EXPOSE 8080
          EOL
          
          # nginx.conf作成
          cat > nginx.conf << 'EOL'
          server {
              listen 8080;
              server_name localhost;
              root /usr/share/nginx/html;
              index index.html;
              location / {
                  try_files $uri $uri/ /index.html;
              }
          }
          EOL

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud config set project flutter-todo-442601
          # ビルドコンテキストの内容を確認
          echo "Current direc